config/routes.rb
Rails.application.routes.draw do


  get 'rate/:profile_id/:mark' , to: 'rate#rate'
  get 'admin/role/:user_id/:role' , to: 'admin#change_role'
  get 'admin/ban/:user_id/:ban' , to: 'admin#ban'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'tags/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'profiles#index'
  resources :admin
  resources :tags,only:[:show]
  resources :profiles do
    resources :photos do
      resources :comments
    end
  end
end



app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :weight,:growth, presence: true
  validates :sex,:year_of_birth, presence: true
  has_many :photos, dependent: :destroy
  belongs_to :photo, dependent: :destroy;
  belongs_to :user, dependent: :destroy;
  serialize :type_of_survey
end

app/controllers/profiles_controller.rb
require 'cloudinary/helper'
include CloudinaryHelper
class ProfilesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_profile, only: [:show,:edit,:update,:destroy]
  before_action :require_user, only: [:edit,:update,:destroy]
  def index
    @profiles = Profile.all
    @profiles.each do |profile|
      profile.mark = find_profile_rating( profile ).to_f
    end
    @profiles =  @profiles.sort_by {|obj| obj.mark}.reverse

  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.photo = Photo.new
    @profile.user = current_user
    if @profile.save
      url = photos_url
      if url
        @profile.photo = @profile.photos.create(:url => url)
        @profile.save
      end
      redirect_to @profile
    else
      render :new
    end
  end

  def edit
  end

  def update
    url = photos_url
    if(url)
      @profile.photo = @profile.photos.create(:url => url)
    end
    if !@profile.photo
      @profile.photo = Photo.new
    end
    if @profile.update_attributes(profile_params)
      redirect_to @profile
    else
      render :edit
    end
  end

  def destroy
    if @profile.photo
      @profile.photo.destroy
    end
    @profile.destroy
    redirect_to root_path
  end


  private

  def require_user
    if current_user
      current_profile = Profile.find_by(user: current_user)
      if current_user.role == "ROLE_ADMIN"
        return
      end
      if params[:id].to_s != current_profile.id.to_s
        redirect_to "/422"
      end
    else
      redirect_to new_user_session_path
    end
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:name,:year_of_birth,:growth,:weight,:sex,:photo,:type_of_survey)
    {:name => params[:profile][:name],
     :year_of_birth => Date.new(params[:profile][:'year_of_birth(1i)'].to_i,params[:profile][:'year_of_birth(2i)'].to_i,params[:profile][:'year_of_birth(3i)'].to_i),
     :growth => params[:profile][:growth], :weight => params[:profile][:weight],
     :sex => params[:profile][:sex],:type_of_survey => params[:profile][:type_of_survey]}
  end


  def photos_url
    if params[:profile][:photo]
      imageCloud = Cloudinary::Uploader.upload( params[:profile][:photo]);
      imageCloud['url']
    else
      nil
    end
  end

  def find_profile_rating( profile )
    ratings = Rating.where(:profile =>profile)
    @rate = 0.0
    if ratings
      ratings.each do|rate|
        @rate = @rate + rate.rate
      end
      if(@rate > 0)
        @rate = @rate.to_f/ratings.size
      end
    end
     @rate
  end


end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def get_avatar(photo)
    if(photo)
      photo.url
    else
      'http://res.cloudinary.com/ddmlz96eh/image/upload/c_limit,h_150,w_100/v1492070468/def_avatar_nfztwr.png'
    end
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f/ max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/profiles/_form.html.erb
<div class="container">
<% if @profile.errors.any? %>

    <div class="alert alert-danger fade in">
      <h5> <%= t('common.errors')%></h5>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
            <li> <%= message%></li>
        <% end%>
      </ul>
    </div>
    <% end%>
<%= form_for @profile do |f|%>
    <div class="form-signin">
    <div class="pad">
      <%= f.label t('profiles.name') ,class:"sr-only"%>
      <%= f.text_field :name, class:'form-control', placeholder:t('profiles.name')%>
    </div>
    <div class="pad">
      <%= f.label t('profiles.growth'),class:"sr-only"%>
      <%= f.text_field :growth, class:'form-control',placeholder:t('profiles.growth')%>
    </div>
    <div class="pad">
      <%= f.label t('profiles.weight'),class:"sr-only"%>
      <%= f.text_field :weight, class:'form-control',placeholder:t('profiles.weight')%>
    </div>

    <div class="form-group">
      <%= f.label t('profiles.year_of_birth')%>
      <%= f.date_select :year_of_birth, :start_year => 1960, :end_year => 1999, class:'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label t('profiles.gender')%>
      <%=select("profile", "sex", [[t('gender.man'),'gender.man'], [t('gender.woman'),'gender.woman'],
        [t('gender.agender'),'gender.agender'], [t('gender.androgyne'),'gender.androgyne'],
        [t('gender.bigender'),'gender.bigender'], [t('gender.FTM'),'gender.FTM'], [t('gender.MTF'),'gender.MTF'],
        [t('gender.transexual'),'gender.transexual'],
        [t('gender.intersex'),'gender.intersex'], [t('gender.fluid') ,'gender.fluid']] , { include_blank: false })%>
    </div>



    <div>
      <p> <%= f.label t('types_of_survey')%></p>

      <p><%=check_box("profile", "type_of_survey", {:multiple => true}, "portrait", nil)%><%= I18n.t('portrait')%> </p>
      <p><%=check_box("profile", "type_of_survey", {:multiple => true}, "nude", nil)%><%= I18n.t('nude')%> </p>
      <p><%=check_box("profile", "type_of_survey", {:multiple => true}, "travel_photography", nil)%><%= I18n.t('travel_photography')%> </p>
      <p><%=check_box("profile", "type_of_survey", {:multiple => true}, "theater", nil)%><%= I18n.t('theater')%> </p>
      <p><%=check_box("profile", "type_of_survey", {:multiple => true}, "street_photo", nil)%><%= I18n.t('street_photo')%> </p>

    </div>

    <%= f.label t('photo.change')%>
    <p><%= f.file_field :photo %></p>

    <div class="form-group">

      <%= f.submit t('savebutton'), class:'btn btn-primary'%>
    </div>
<%end%>
</div>
</div>

app/views/profiles/_profile.html.erb
<div class="card card-block" style="margin-top:20px" >
  <section class="post-head">
    <h3 class="card-title"><%=link_to profile.name,profile_path(profile), class:"card-link"%></h3>
  </section>
  <section class="post-summary clearfix">
    <%=image_tag(get_avatar(profile.photo), :width => 100, :height => 150,:crop => :scale,:class => 'img-thumbnail thumb')%>
  </section>
  <% find_profile_rating(profile)%>
  <% @rate %>
  <section>
    <%= render 'rate_withoult_links'%>
  </section>
</div>

app/views/profiles/_rate.html.erb

<script type="application/javascript">
    $.when( $.ready ).then(function() {
        $('.link_star').on("ajax:success", function(e, data, status, xhr) {
            $('#rating_div').html(data);

        } );

    });
</script>

<div id = "rating_div">
<p class="card-text">
  <% find_profile_rating(@profile)%>
  <%= I18n.t('profile')%>:
  <%if @rate > 0 %>
      <%= image_tag("stars/star-on.svg") %>
  <%else%>
      <%= image_tag("stars/star-off.svg") %>
  <% end %>

  <%if @rate > 1 %>
      <%= image_tag("stars/star-on.svg") %>
  <%else%>
      <%= image_tag("stars/star-off.svg") %>
  <% end %>

  <%if @rate > 2 %>
      <%= image_tag("stars/star-on.svg") %>
  <%else%>
      <%= image_tag("stars/star-off.svg") %>
  <% end %>

  <%if @rate > 3 %>
      <%= image_tag("stars/star-on.svg") %>
  <%else%>
      <%= image_tag("stars/star-off.svg") %>
  <% end %>

  <%if @rate > 4 %>
      <%= image_tag("stars/star-on.svg") %>
  <%else%>
      <%= image_tag("stars/star-off.svg") %>
  <% end %>
  </p>
<% if current_user %>
<p class="card-text">
  <% find_user_rating(@profile)%>
  <%= I18n.t('my')%>:
  <%if @rate > 0 %>
      <%=link_to("/rate/"+@profile.id.to_s+"/1", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-on.svg") %>
      <% end %>
  <%else%>
      <%=link_to("/rate/"+@profile.id.to_s+"/1", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-off.svg") %>
      <% end %>
  <% end %>

  <%if @rate > 1 %>
      <%=link_to("/rate/"+@profile.id.to_s+"/2", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-on.svg") %>
      <% end %>
  <%else%>
      <%=link_to("/rate/"+@profile.id.to_s+"/2", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-off.svg") %>
      <% end %>
  <% end %>

  <%if @rate > 2 %>
      <%=link_to("/rate/"+@profile.id.to_s+"/3", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-on.svg") %>
      <% end %>
  <%else%>
      <%=link_to("/rate/"+@profile.id.to_s+"/3", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-off.svg") %>
      <% end %>
  <% end %>

  <%if @rate > 3 %>
      <%=link_to("/rate/"+@profile.id.to_s+"/4", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-on.svg") %>
      <% end %>
  <%else%>
      <%=link_to("/rate/"+@profile.id.to_s+"/4", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-off.svg") %>
      <% end %>
  <% end %>

  <%if @rate > 4 %>
      <%=link_to("/rate/"+@profile.id.to_s+"/5", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-on.svg") %>
      <% end %>
  <%else%>
      <%=link_to("/rate/"+@profile.id.to_s+"/5", remote:true,class: "link_star") do%>
          <%= image_tag("stars/star-off.svg") %>
      <% end %>
  <% end %>
</p>
  <% end %>
</div>

app/views/profiles/_rate_withoult_links.html.erb
<%if @rate > 0 %>
    <%= image_tag("stars/star-on.svg") %>
<%else%>
    <%= image_tag("stars/star-off.svg") %>
<% end %>

<%if @rate > 1 %>
    <%= image_tag("stars/star-on.svg") %>
<%else%>
    <%= image_tag("stars/star-off.svg") %>
<% end %>

<%if @rate > 2 %>
    <%= image_tag("stars/star-on.svg") %>
<%else%>
    <%= image_tag("stars/star-off.svg") %>
<% end %>

<%if @rate > 3 %>
    <%= image_tag("stars/star-on.svg") %>
<%else%>
    <%= image_tag("stars/star-off.svg") %>
<% end %>

<%if @rate > 4 %>
    <%= image_tag("stars/star-on.svg") %>
<%else%>
    <%= image_tag("stars/star-off.svg") %>
<% end %>

app/views/profiles/edit.html.erb
<h2 class="form-signin-heading"><%= I18n.t('profiles.edit')%></h2>
<%= render 'form'%>

app/views/profiles/index.html.erb
<%= render @profiles%>

app/views/profiles/new.html.erb
<h2><%= I18n.t('profiles.new')%></h2>

<%= render 'form'%>

app/views/profiles/show.html.erb

<script type='text/javascript' src="//code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
<script type='text/javascript' src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>



  <div class="card card-block" style="margin-top:20px" >
    <h3 class="card-title"><%=@profile.name%></h3>
    <figure>
      <%=image_tag(get_avatar(@profile.photo), :width => 200, :height => 200,:crop => :scale,:class => 'img-thumbnail')%>
    </figure>
    <p class="card-text"><strong><%= I18n.t('info.birthday')%> </strong> <%=@profile.year_of_birth%></p>
    <p class="card-text"><strong><%= I18n.t('info.weight')%> </strong> <%=@profile.weight%></p>
    <p class="card-text"><strong><%= I18n.t('info.growth')%> </strong> <%=@profile.growth%></p>
    <p class="card-text"><strong><%= I18n.t('info.sex')%> </strong> <%=t(@profile.sex)%></p>
    <p class="card-text"><strong><%= I18n.t('types_of_survey')%>: </strong></p>
    <% if @profile.type_of_survey.kind_of?(Array)%>
        <ul>
          <%@profile.type_of_survey.each do|type|%>
            <li><%=t(type)%></li>
          <%end%>
      </ul>
    <% end %>
    <p><%= render 'rate'%></p>
    <p>
      <%@profile_id = @profile.id%>
      <%if require_user %>
        <%= link_to t('profiles.edit'), edit_profile_path(@profile), class:"card-link"%>
        <%= link_to t('profiles.delete'), profile_path(@profile),method: :delete,data: {confirm:'Are u shure?'}, class:"card-link"%></p>
      <% end %>
  </div>



<div class="card card-block" style="margin-top:20px" >
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="card-title"><%= I18n.t('photo.title')%></h3>
  </div>
  <div class="panel-body" style="margin-top: 10px;">
    <div class="row sortable" >

  <%@profile.photos.each do |photo|%>
          <!--div class="col-md-3 thumb size"-->
          <div class="card">
          <a  href="<%=profile_photo_path(@profile,photo)%>" onclick="imageClick(this)" data-toggle="modal" data-target="#exampleModalLong" >
            <%#=image_tag(photo.url,:class => 'img-thumbnail thumb')%>
            <%= cl_image_tag(photo.url,:height => 200, :crop => :scale)%>
          </a>
            </div>
        <!--/div-->
<%end%>
  </div>
</div>
</div>
</div>

<script type='text/javascript'>
    $(".sortable").sortable({
        items       : 'div:not(.unsortable)',
        placeholder : 'sortable-placeholder',
        update: function(event, ui) {
            // console.log(event);
            // console.log(ui.placeholder.index() + " :  " + ui.placeholder);
            console.log(ui.item.index()+" "+ ui.item.html());
        }
    });
    $(".sortable").disableSelection();

</script>

<% if require_user %>
  <h2><%= I18n.t('photo.add')%></h2>
  <%= render 'photos/form' %>
<% end %>



<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"></h5>
        <button type="button" onclick="stopUpdateComment()" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="stopUpdateComment()" ><%= I18n.t('photo.close')%></button>
      </div>
    </div>
  </div>
</div>