config/routes.rb
Rails.application.routes.draw do


  get 'rate/:profile_id/:mark' , to: 'rate#rate'
  get 'admin/role/:user_id/:role' , to: 'admin#change_role'
  get 'admin/ban/:user_id/:ban' , to: 'admin#ban'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'tags/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'profiles#index'
  resources :admin
  resources :tags,only:[:show]
  resources :profiles do
    resources :photos do
      resources :comments
    end
  end
end



app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :photos, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
  end
end

app/views/tags/show.html.erb

<h1><%= @tag.name %></h1>
<% @tag.photos.each do |photo|%>
    <article class="profiles">
      <p class="card-text"><strong><a  href="<%=profile_path(photo.profile)%>" class="card-link"><h4><%= photo.profile.name%></h4></a></strong></p>
      <a  href="<%=profile_photo_path(photo.profile,photo)%>" onclick="imageClick(this)" data-toggle="modal" data-target="#exampleModalLong" >
      <section class="post-summary clearfix">
        <%=image_tag(photo.url, :width => 100, :height => 150,:crop => :scale,:class => 'img-thumbnail thumb')%>
      </section>
      </a>
      <%= raw photo.tags.map(&:name).map{ |t| link_to t,tag_path(t) ,class:'badge badge-primary'}.join(' ')%>
    </article>
<% end %>

<div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"></h5>
        <button type="button" onclick="stopUpdateComment()" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="stopUpdateComment()" ><%= I18n.t('photo.close')%></button>
      </div>
    </div>
  </div>
</div>
