config/routes.rb
Rails.application.routes.draw do


  get 'rate/:profile_id/:mark' , to: 'rate#rate'
  get 'admin/role/:user_id/:role' , to: 'admin#change_role'
  get 'admin/ban/:user_id/:ban' , to: 'admin#ban'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'tags/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'profiles#index'
  resources :admin
  resources :tags,only:[:show]
  resources :profiles do
    resources :photos do
      resources :comments
    end
  end
end



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Portfl</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <div class="container">
    <div class="header clearfix">
      <nav>
        <ul class="nav float-right">
          <li class="button<%= " active" if I18n.locale == :ru %>"><%= link_to "Рус", {locale: :ru}, class: "nav-link" %></li>
          <li class="button<%= " active" if I18n.locale == :en %>"><%= link_to "Eng", {locale: :en}, class: "nav-link" %></li>
          <% if !create_profile%>
            <li class="button"> <a href="<%=profiles_path%>" class="list-group-item"><%= I18n.t('profiles.list')%> </a></li>
          <% end %>
          <% if get_my_profile %>
              <li class="button"><%=link_to I18n.t('my_profile'), profile_path(get_my_profile), class:"list-group-item" %></a></li>
          <% end %>
          <%if user_signed_in? %>
              <li class="button"><%=link_to I18n.t('logout'), destroy_user_session_path, class:"list-group-item" ,method: :delete%></a></li>
          <% else %>
              <li class="button"><%=  link_to I18n.t('login'), new_user_session_path, class:"list-group-item"%></a></li>
          <% end %>
          <% if  !user_signed_in? %>
              <li class="button"><a href="/users/sign_up" class="list-group-item"><%= I18n.t('registration')%></a></li>
          <% end %>
          <% if  require_admin %>
              <li class="button"><a href="/admin" class="list-group-item"><%= I18n.t('admin_page')%></a></li>
          <% end %>
        </ul>
      </nav>
      <h3 class="text-muted">Portfl</h3>
    </div>
  </div>


  <% if ban%>
      <div class="alert alert-danger" style="width: 400px;margin: auto" role="alert"><%= t('ti_ban')%></div>
  <% else %>
  <% if create_profile%>
      <% @profile = Profile.new %>
      <%= render 'profiles/form'%>
  <%else%>



  <div class="container">
  <div class="row row-offcanvas row-offcanvas-right">
      <div class="col-xs-10 col-sm-9">
        <%= yield %>
      </div>

      <div class="col-xs-10 col-sm-3 sidebar-offcanvas" id="top">
        <div class="list-group">

          <a class="list-group-item">
            <%= I18n.t('search.profiles')%>
          </a>
          <a class="list-group-item">

            <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="<%= I18n.t('search.placeholder')%>">
              </div>
              <button type="submit" class="btn btn-default"><%= I18n.t('search.button')%></button>
            </form>

          </a>
        </div><br><br>
        <h3 align='center'> <%= I18n.t('tags')%></h3>
        <% tag_cloud(Tag.counts,%w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class|%>
            <%= link_to tag.name,tag_path(tag.name) ,class:css_class%>
        <% end %>
      </div>
  </div>
  </div>
  <%end%>
      <% end %>
  </body>
</html>